/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRepertorioRouteImport } from './routes/_authenticated/repertorio'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedEscalaRouteImport } from './routes/_authenticated/escala'
import { Route as AuthenticatedCultoRouteImport } from './routes/_authenticated/culto'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRepertorioRoute = AuthenticatedRepertorioRouteImport.update({
  id: '/repertorio',
  path: '/repertorio',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEscalaRoute = AuthenticatedEscalaRouteImport.update({
  id: '/escala',
  path: '/escala',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCultoRoute = AuthenticatedCultoRouteImport.update({
  id: '/culto',
  path: '/culto',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/culto': typeof AuthenticatedCultoRoute
  '/escala': typeof AuthenticatedEscalaRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/repertorio': typeof AuthenticatedRepertorioRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/culto': typeof AuthenticatedCultoRoute
  '/escala': typeof AuthenticatedEscalaRoute
  '/perfil': typeof AuthenticatedPerfilRoute
  '/repertorio': typeof AuthenticatedRepertorioRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/culto': typeof AuthenticatedCultoRoute
  '/_authenticated/escala': typeof AuthenticatedEscalaRoute
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/_authenticated/repertorio': typeof AuthenticatedRepertorioRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/auth' | '/culto' | '/escala' | '/perfil' | '/repertorio'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/auth' | '/culto' | '/escala' | '/perfil' | '/repertorio'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/culto'
    | '/_authenticated/escala'
    | '/_authenticated/perfil'
    | '/_authenticated/repertorio'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/repertorio': {
      id: '/_authenticated/repertorio'
      path: '/repertorio'
      fullPath: '/repertorio'
      preLoaderRoute: typeof AuthenticatedRepertorioRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/escala': {
      id: '/_authenticated/escala'
      path: '/escala'
      fullPath: '/escala'
      preLoaderRoute: typeof AuthenticatedEscalaRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/culto': {
      id: '/_authenticated/culto'
      path: '/culto'
      fullPath: '/culto'
      preLoaderRoute: typeof AuthenticatedCultoRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCultoRoute: typeof AuthenticatedCultoRoute
  AuthenticatedEscalaRoute: typeof AuthenticatedEscalaRoute
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedRepertorioRoute: typeof AuthenticatedRepertorioRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCultoRoute: AuthenticatedCultoRoute,
  AuthenticatedEscalaRoute: AuthenticatedEscalaRoute,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedRepertorioRoute: AuthenticatedRepertorioRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
