GRANT SELECT, INSERT, UPDATE, DELETE ON public.profiles TO authenticated;
GRANT ALL ON public.profiles TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.user_roles TO authenticated;
GRANT ALL ON public.user_roles TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.cantores TO authenticated;
GRANT ALL ON public.cantores TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.instrumentistas TO authenticated;
GRANT ALL ON public.instrumentistas TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.musicas TO authenticated;
GRANT ALL ON public.musicas TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.cantor_tons TO authenticated;
GRANT ALL ON public.cantor_tons TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.cultos TO authenticated;
GRANT ALL ON public.cultos TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.integrantes_culto TO authenticated;
GRANT ALL ON public.integrantes_culto TO service_role;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.repertorio_culto TO authenticated;
GRANT ALL ON public.repertorio_culto TO service_role;
GRANT USAGE ON SCHEMA public TO authenticated, anon, service_role;